import { Booking, CareEvent, Caregiver, Customer, JobRequest, Review } from "./types";

export const MOCK_CAREGIVERS: Caregiver[] = [
  {
    id: "cg-001",
    name: "Lakshmi Devi",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lakshmi&backgroundColor=c0aede",
    phone: "+91 98765 43210",
    email: "lakshmi.d@email.com",
    location: "Banjara Hills, Hyderabad",
    city: "Hyderabad",
    languages: ["Telugu", "Hindi", "English"],
    experience: 8,
    skills: ["Mobility assistance", "Medicine reminders", "Companion care", "Feeding assistance", "Dementia care"],
    bio: "Experienced caregiver with 8 years of dedicated service to elderly patients. Specializes in dementia care and mobility assistance. Known for patience and warmth.",
    hourlyRate: 350,
    dailyRate: 2500,
    rating: 4.9,
    reviewCount: 127,
    completedBookings: 340,
    identityVerified: true,
    backgroundVerified: true,
    certifications: ["Certified Caregiver - NAC", "First Aid Certified"],
    availability: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    isAvailable: true,
    verificationStatus: "verified",
    joinedAt: "2021-03-15",
  },
  {
    id: "cg-002",
    name: "Rajesh Kumar",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rajesh&backgroundColor=b6e3f4",
    phone: "+91 98765 43211",
    email: "rajesh.k@email.com",
    location: "Jubilee Hills, Hyderabad",
    city: "Hyderabad",
    languages: ["Telugu", "Hindi", "English", "Urdu"],
    experience: 5,
    skills: ["Hospital accompaniment", "Mobility assistance", "Post-surgery care", "Medicine reminders"],
    bio: "Reliable caregiver specializing in hospital visits and post-surgery recovery support. Excellent at navigating hospitals and coordinating with medical staff.",
    hourlyRate: 400,
    dailyRate: 2800,
    rating: 4.8,
    reviewCount: 89,
    completedBookings: 210,
    identityVerified: true,
    backgroundVerified: true,
    certifications: ["Patient Care Attendant Certificate"],
    availability: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sun"],
    isAvailable: true,
    verificationStatus: "verified",
    joinedAt: "2022-06-20",
  },
  {
    id: "cg-003",
    name: "Sunita Reddy",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sunita&backgroundColor=ffd5dc",
    phone: "+91 98765 43212",
    email: "sunita.r@email.com",
    location: "Gachibowli, Hyderabad",
    city: "Hyderabad",
    languages: ["Telugu", "English"],
    experience: 12,
    skills: ["Bedridden care", "Overnight care", "Bathing & grooming", "Feeding assistance", "Diabetes management"],
    bio: "Senior caregiver with over 12 years of experience in bedridden and overnight patient care. Trained in diabetes management and wound care basics.",
    hourlyRate: 450,
    dailyRate: 3200,
    rating: 4.95,
    reviewCount: 203,
    completedBookings: 520,
    identityVerified: true,
    backgroundVerified: true,
    certifications: ["Advanced Patient Care", "Diabetes Care Specialist", "First Aid"],
    availability: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    isAvailable: true,
    verificationStatus: "verified",
    joinedAt: "2019-01-10",
  },
  {
    id: "cg-004",
    name: "Mohammed Ali",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mohammed&backgroundColor=d1d4f9",
    phone: "+91 98765 43213",
    email: "mohammed.a@email.com",
    location: "Secunderabad, Hyderabad",
    city: "Hyderabad",
    languages: ["Urdu", "Hindi", "Telugu", "English"],
    experience: 6,
    skills: ["Hospital accompaniment", "Mobility assistance", "Medicine reminders", "Companion care"],
    bio: "Compassionate attendant with strong experience in hospital visits and elderly companion care. Fluent in multiple languages.",
    hourlyRate: 380,
    dailyRate: 2600,
    rating: 4.7,
    reviewCount: 76,
    completedBookings: 185,
    identityVerified: true,
    backgroundVerified: true,
    certifications: ["Caregiver Training Certificate"],
    availability: ["Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    isAvailable: true,
    verificationStatus: "verified",
    joinedAt: "2022-11-05",
  },
  {
    id: "cg-005",
    name: "Priya Sharma",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Priya&backgroundColor=c0aede",
    phone: "+91 98765 43214",
    email: "priya.s@email.com",
    location: "Madhapur, Hyderabad",
    city: "Hyderabad",
    languages: ["Hindi", "English", "Telugu"],
    experience: 4,
    skills: ["Companion care", "Feeding assistance", "Bathing & grooming", "Medicine reminders"],
    bio: "Young and energetic caregiver passionate about elderly care. Great with daily routines and creating a positive environment.",
    hourlyRate: 300,
    dailyRate: 2200,
    rating: 4.6,
    reviewCount: 45,
    completedBookings: 98,
    identityVerified: true,
    backgroundVerified: false,
    certifications: ["Basic Caregiver Training"],
    availability: ["Mon", "Wed", "Fri", "Sat", "Sun"],
    isAvailable: true,
    verificationStatus: "verified",
    joinedAt: "2023-08-12",
  },
  {
    id: "cg-006",
    name: "Venkat Rao",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Venkat&backgroundColor=b6e3f4",
    phone: "+91 98765 43215",
    email: "venkat.r@email.com",
    location: "Kukatpally, Hyderabad",
    city: "Hyderabad",
    languages: ["Telugu", "Hindi"],
    experience: 10,
    skills: ["Physiotherapy support", "Mobility assistance", "Post-surgery care", "Overnight care"],
    bio: "Experienced in post-surgery rehabilitation support and physiotherapy assistance. Strong background in mobility training for elderly patients.",
    hourlyRate: 420,
    dailyRate: 3000,
    rating: 4.85,
    reviewCount: 156,
    completedBookings: 410,
    identityVerified: true,
    backgroundVerified: true,
    certifications: ["Physiotherapy Assistant", "Patient Care Advanced"],
    availability: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    isAvailable: false,
    verificationStatus: "verified",
    joinedAt: "2020-05-22",
  },
];

export const MOCK_CUSTOMER: Customer = {
  id: "cust-001",
  name: "Arjun Mehta",
  email: "arjun.mehta@email.com",
  phone: "+91 99887 76655",
  emergencyContact: "Priya Mehta (Wife)",
  emergencyPhone: "+91 99887 76656",
};

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: "bk-001",
    customerId: "cust-001",
    customerName: "Arjun Mehta",
    caregiverId: "cg-001",
    caregiverName: "Lakshmi Devi",
    serviceCategory: "elderly-care",
    serviceName: "Elderly Care - Daily Assistance",
    requirement: "Need companion care for my 78-year-old father with mobility issues",
    location: "Banjara Hills, Hyderabad",
    date: new Date().toISOString().split("T")[0],
    startTime: "09:00",
    duration: 8,
    totalAmount: 2800,
    status: "in-progress",
    paymentStatus: "paid",
    patientName: "Ramesh Mehta (Dad)",
    patientAge: 78,
    checkInTime: "09:02",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "bk-002",
    customerId: "cust-001",
    customerName: "Arjun Mehta",
    caregiverId: "cg-002",
    caregiverName: "Rajesh Kumar",
    serviceCategory: "hospital-assistance",
    serviceName: "Hospital & Doctor Assistance",
    requirement: "Accompany father to hospital appointment at Apollo",
    location: "Jubilee Hills, Hyderabad",
    date: new Date(Date.now() + 86400000 * 2).toISOString().split("T")[0],
    startTime: "10:00",
    duration: 5,
    totalAmount: 2000,
    status: "confirmed",
    paymentStatus: "paid",
    patientName: "Ramesh Mehta (Dad)",
    patientAge: 78,
    createdAt: new Date().toISOString(),
  },
  {
    id: "bk-003",
    customerId: "cust-001",
    customerName: "Arjun Mehta",
    caregiverId: "cg-003",
    caregiverName: "Sunita Reddy",
    serviceCategory: "patient-care",
    serviceName: "Patient Care - Overnight Attendant",
    requirement: "Overnight care for bedridden mother after hip surgery",
    location: "Gachibowli, Hyderabad",
    date: new Date(Date.now() - 86400000 * 7).toISOString().split("T")[0],
    startTime: "20:00",
    duration: 12,
    totalAmount: 5400,
    status: "completed",
    paymentStatus: "paid",
    patientName: "Savitri Mehta (Mom)",
    patientAge: 72,
    checkInTime: "20:05",
    checkOutTime: "08:10",
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
];

export const MOCK_CARE_EVENTS: CareEvent[] = [
  {
    id: "ce-001",
    bookingId: "bk-001",
    title: "Caregiver arrived",
    timestamp: "09:02 AM",
    type: "check-in",
  },
  {
    id: "ce-002",
    bookingId: "bk-001",
    title: "Breakfast assistance completed",
    description: "Helped with morning meal and medication",
    timestamp: "09:30 AM",
    type: "activity",
  },
  {
    id: "ce-003",
    bookingId: "bk-001",
    title: "Medicine reminder",
    description: "Blood pressure medication administered",
    timestamp: "10:00 AM",
    type: "medication",
  },
  {
    id: "ce-004",
    bookingId: "bk-001",
    title: "Morning walk assistance",
    description: "15-minute walk in the garden with walker support",
    timestamp: "10:30 AM",
    type: "activity",
  },
  {
    id: "ce-005",
    bookingId: "bk-001",
    title: "Lunch preparation & feeding",
    timestamp: "12:30 PM",
    type: "activity",
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "rev-001",
    bookingId: "bk-003",
    customerId: "cust-001",
    customerName: "Arjun Mehta",
    caregiverId: "cg-003",
    rating: 5,
    comment: "Sunita was exceptional during my mother's recovery. Very attentive, professional, and caring throughout the night.",
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "rev-002",
    bookingId: "bk-old-001",
    customerId: "cust-002",
    customerName: "Kavitha Nair",
    caregiverId: "cg-001",
    rating: 5,
    comment: "Lakshmi took wonderful care of my father. Her patience with his dementia was remarkable. Highly recommended!",
    createdAt: new Date(Date.now() - 86400000 * 15).toISOString(),
  },
  {
    id: "rev-003",
    bookingId: "bk-old-002",
    customerId: "cust-003",
    customerName: "Suresh Patel",
    caregiverId: "cg-002",
    rating: 4,
    comment: "Rajesh was very helpful during my hospital visit. Knew the hospital well and made the process smooth.",
    createdAt: new Date(Date.now() - 86400000 * 20).toISOString(),
  },
];

export const MOCK_JOB_REQUESTS: JobRequest[] = [
  {
    id: "jr-001",
    bookingId: "bk-pending-001",
    customerName: "Kavitha Nair",
    serviceName: "Elderly Care - Companion",
    location: "Hitech City, Hyderabad",
    date: new Date(Date.now() + 86400000).toISOString().split("T")[0],
    startTime: "08:00",
    duration: 8,
    amount: 2800,
    requirement: "Companion care for 82-year-old grandmother, needs Telugu-speaking caregiver",
    status: "pending",
    createdAt: new Date().toISOString(),
  },
  {
    id: "jr-002",
    bookingId: "bk-pending-002",
    customerName: "Ravi Teja",
    serviceName: "Hospital Assistance",
    location: "Ameerpet, Hyderabad",
    date: new Date(Date.now() + 86400000 * 2).toISOString().split("T")[0],
    startTime: "14:00",
    duration: 4,
    amount: 1600,
    requirement: "Need someone to accompany my father to cardiologist appointment",
    status: "pending",
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
];

export const TESTIMONIALS = [
  {
    name: "Kavitha Nair",
    location: "Hyderabad",
    text: "Finding reliable care for my 82-year-old grandmother was always stressful. SaathiCare made it so simple — verified caregivers, real-time updates, and peace of mind.",
    rating: 5,
    service: "Elderly Care",
  },
  {
    name: "Ravi Teja",
    location: "Hyderabad",
    text: "When my father needed hospital accompaniment, Rajesh was there every step of the way. The family dashboard kept us informed throughout.",
    rating: 5,
    service: "Hospital Assistance",
  },
  {
    name: "Priya Sharma",
    location: "Hyderabad",
    text: "After my mother's hip surgery, Sunita's overnight care was a blessing. Professional, caring, and always on time with medications.",
    rating: 5,
    service: "Patient Care",
  },
];
